# Default values for KubeBackup
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image:
  repository: docker.io/cube8021/kubebackup
  tag: DRONE_BUILD_NUMBER
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

annotations: {}
labels:
  kubernetes.io/name: "KubeBackup"

extraEnv: []
podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

rbac:
  create: true

  clusterAdminRole: true

secrets:
  s3:
    region: us-east-1
    bucket: my-bucket
    accessKey: ""
    secretKey: ""

serviceAccount:
  create: true
  name: kubebackup

securityContext: {}
