# Default values for KubeBackup
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image:
  repository: docker.io/cube8021/kubebackup
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

annotations: {}
labels:
  kubernetes.io/name: "KubeBackup"

extraEnv: []
podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

rbac:
  create: true

  clusterAdminRole: true

secrets:
  s3:
    bucket: my-bucket
    folder: "my-cluster"
    region: us-east-1
    endpoint: ""
    accessKey: ""
    secretKey: ""

serviceAccount:
  create: true
  name: kubebackup

securityContext: {}

settings:
  interval: 12h
  retention: 30d
  backupDir: /var/lib/kubebackup
  loglevel: info

metrics:
  enabled: true
  port: 9009
  path: /metrics
  alertmanager:
    enabled: false
    url: ""
    interval: 5m
    labels:
      severity: warning
    annotations:
      summary: "KubeBackup alert"
      description: "KubeBackup is not running"