apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "kubebackup.name" . }}
    chart: {{ template "kubebackup.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kubebackup.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  s3-bucket: {{ .Values.s3.bucket | b64enc | quote }}
  s3-folder: {{ .Values.s3.folder | b64enc | quote }}
  s3-region: {{ .Values.s3.region | b64enc | quote }}
  s3-endpoint: {{ .Values.s3.endpoint | b64enc | quote }}
  s3-access-key": {{ .Values.s3.accessKey | b64enc | quote }}
  s3-secret-key: {{ .Values.s3.secretKey | b64enc | quote }}
