name: Build, Test and Publish

on:
  push:
    branches:
      - master

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod download

      - name: Build Go script
        run: make build

      - name: Run tests
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: | 
          make docker-build
          docker push cube8021/kubebackup:latest

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Package Helm chart
        run: |
          CHART_VERSION="0.1.${GITHUB_RUN_NUMBER}"
          APP_VERSION="0.1.${GITHUB_RUN_NUMBER}"
          envsubst < helm/kubebackup/Chart.yaml.template > helm/kubebackup/Chart.yaml
          envsubst < helm/kubebackup/values.yaml.template > helm/kubebackup/values.yaml
          helm package helm/kubebackup --destination helm/repo

      - name: Checkout helm-chart repository
        uses: actions/checkout@v2
        with:
          repository: SupportTools/helm-chart
          path: helm-chart
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Update Helm repository
        run: |
          cp chart-output/*.tgz helm-chart/
          cd helm-chart
          helm repo index . --url https://charts.support.tools/
          git add .
          git commit -m "Update Helm chart for KubeBackup"
          git push